In [2]:
import pandas as pd
from joblib import load

In [3]:
testing_df = pd.read_csv('../../data/5-prediction/input/data_prediksi.csv') 
testing_df

,UniProt ID,ANDN920101,ARGP820101,ARGP820102,ARGP820103,BEGF750101,BEGF750102,BEGF750103,BHAR880101,BIGC670101,...,1015,1016,1017,1018,1019,1020,1021,1022,1023,Drug
0,O15379,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,...,0,0,0,0,0,0,0,0,0,4-aminobenzoic acid
1,O15379,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,...,0,0,0,0,0,0,0,0,0,Citric acid
2,O15379,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,...,0,0,1,0,0,0,0,0,0,L-phenylalanine
3,O15379,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,...,0,0,0,0,0,0,0,0,0,Trans-3-indoleacrylic acid
4,O15379,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,...,0,0,0,0,0,0,0,0,0,DL-tryptophan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,Q7Z4H4,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,...,0,0,1,0,0,0,0,0,0,Murralongin
2036,Q7Z4H4,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,...,0,0,0,0,1,0,0,0,0,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(..."
2037,Q7Z4H4,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,...,0,0,1,0,1,1,0,1,0,"Limonene, (+/-)-"
2038,Q7Z4H4,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,...,0,0,0,0,1,0,0,0,0,Pheophorbide a
2039,Q7Z4H4,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,...,0,0,0,0,0,0,0,0,0,SB236057

In [4]:
inter_df = testing_df[['UniProt ID','Drug']]
inter_df

     UniProt ID                                               Drug
0        O15379                               4-aminobenzoic acid
1        O15379                                        Citric acid
2        O15379                                   L-phenylalanine
3        O15379                         Trans-3-indoleacrylic acid
4        O15379                                      DL-tryptophan
...         ...                                                ...
2035     Q7Z4H4                                        Murralongin
2036     Q7Z4H4  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...
2037     Q7Z4H4                                  Limonene, (+/-)-
2038     Q7Z4H4                                     Pheophorbide a
2039     Q7Z4H4                                          SB236057

[2040 rows x 2 columns]

In [5]:
testing_dff = testing_df.drop(columns=['UniProt ID','Drug'])
testing_dff

,ANDN920101,ARGP820101,ARGP820102,ARGP820103,BEGF750101,BEGF750102,BEGF750103,BHAR880101,BIGC670101,BIOV880101,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
0,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,0.46468,...,0,0,0,0,0,0,0,0,0,0
1,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,0.46468,...,0,0,0,0,0,0,0,0,0,0
2,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,0.46468,...,0,0,0,1,0,0,0,0,0,0
3,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,0.46468,...,0,0,0,0,0,0,0,0,0,0
4,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,0.46468,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,-0.56185,...,0,0,0,1,0,0,0,0,0,0
2036,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,-0.56185,...,0,0,0,0,0,1,0,0,0,0
2037,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,-0.56185,...,0,0,0,1,0,1,1,0,1,0
2038,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,-0.56185,...,0,0,0,0,0,1,0,0,0,0
2039,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,-0.56185,...,0,0,0,0,0,0,0,0,0,0

In [6]:
testing_dff.columns = range(len(testing_dff.columns))
testing_dff

,0,1,2,3,4,5,6,7,8,9,...,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576
0,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,0.46468,...,0,0,0,0,0,0,0,0,0,0
1,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,0.46468,...,0,0,0,0,0,0,0,0,0,0
2,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,0.46468,...,0,0,0,1,0,0,0,0,0,0
3,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,0.46468,...,0,0,0,0,0,0,0,0,0,0
4,1.481179,0.352386,-0.917555,-0.859283,-0.851430,0.637549,0.663336,-0.204360,0.324345,0.46468,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,-0.56185,...,0,0,0,1,0,0,0,0,0,0
2036,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,-0.56185,...,0,0,0,0,0,1,0,0,0,0
2037,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,-0.56185,...,0,0,0,1,0,1,1,0,1,0
2038,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,-0.56185,...,0,0,0,0,0,1,0,0,0,0
2039,-1.267287,-1.212851,0.183289,-0.144650,-2.238365,-1.291810,2.493396,1.960063,-2.018917,-0.56185,...,0,0,0,0,0,0,0,0,0,0

### Prediksi menggunakan Model Random Forest

In [7]:
model = load('../../data/4-modelling/result/bindingdb/AAIndex-Morgan/best_model_random_forest.joblib')

In [8]:
print(type(model))

<class 'sklearn.ensemble._forest.RandomForestClassifier'>

In [9]:
hasil_prediksi = model.predict(testing_dff)
hasil_prediksi

array([1, 1, 1, ..., 1, 1, 1])

In [10]:
proba = model.predict_proba(testing_dff)
proba

array([[0.12, 0.88],
       [0.1 , 0.9 ],
       [0.12, 0.88],
       ...,
       [0.48, 0.52],
       [0.46, 0.54],
       [0.4 , 0.6 ]])

In [11]:
# Menggunakan .predict_proba() untuk mendapatkan probabilitas prediksi
y_proba = model.predict_proba(testing_dff)[:, 1]  # Probabilitas untuk kelas 1

# Menetapkan threshold 0.9 untuk prediksi kelas 1
threshold = 0.95
y_pred_custom = (y_proba >= threshold).astype(int)

print("Probabilitas prediksi untuk kelas 1:", y_proba)
print("Prediksi dengan threshold 0.8:", y_pred_custom)

Probabilitas prediksi untuk kelas 1: [0.88 0.9  0.88 ... 0.52 0.54 0.6 ]
Prediksi dengan threshold 0.8: [0 0 0 ... 0 0 0]

In [12]:
hasil = pd.DataFrame(y_proba)
hasil

         0
0     0.88
1     0.90
2     0.88
3     0.90
4     0.88
...    ...
2035  0.54
2036  0.50
2037  0.52
2038  0.54
2039  0.60

[2040 rows x 1 columns]

In [13]:
result = pd.concat([inter_df, hasil], axis=1)
result

     UniProt ID                                               Drug     0
0        O15379                               4-aminobenzoic acid   0.88
1        O15379                                        Citric acid  0.90
2        O15379                                   L-phenylalanine   0.88
3        O15379                         Trans-3-indoleacrylic acid  0.90
4        O15379                                      DL-tryptophan  0.88
...         ...                                                ...   ...
2035     Q7Z4H4                                        Murralongin  0.54
2036     Q7Z4H4  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...  0.50
2037     Q7Z4H4                                  Limonene, (+/-)-   0.52
2038     Q7Z4H4                                     Pheophorbide a  0.54
2039     Q7Z4H4                                          SB236057   0.60

[2040 rows x 3 columns]

In [14]:
df_sorted = result.sort_values(by=0, ascending=False)
# df_sorted = df_sorted.head(10)
df_sorted

     UniProt ID                        Drug     0
825      P32249        4-aminobenzoic acid   0.94
1863     Q96DB2  Trans-3-indoleacrylic acid  0.94
1260     P17612        4-aminobenzoic acid   0.92
1612     P15692             Alpha-lapachone  0.90
211      P10275                 Citric acid  0.90
...         ...                         ...   ...
987      P42345           Limonene, (+/-)-   0.04
1339     P43405               DL-tryptophan  0.04
1337     P43405            L-phenylalanine   0.04
522      Q96PN6           Limonene, (+/-)-   0.02
1338     P43405  Trans-3-indoleacrylic acid  0.02

[2040 rows x 3 columns]

In [15]:
filter1_df = df_sorted[df_sorted[0] > 0.95]
filter1_df

Empty DataFrame
Columns: [UniProt ID, Drug, 0]
Index: []

In [16]:

# Membuat distribusi normal dari kolom
# Kita melakukan standarisasi nilai menjadi distribusi normal dengan mean 0 dan std 1
mean_value = df_sorted[0].mean()
std_value = df_sorted[0].std()
df_sorted['Z_Score'] = (df_sorted[0] - mean_value) / std_value

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted

     UniProt ID                        Drug     0   Z_Score
825      P32249        4-aminobenzoic acid   0.94  2.311711
1863     Q96DB2  Trans-3-indoleacrylic acid  0.94  2.311711
1260     P17612        4-aminobenzoic acid   0.92  2.200322
1612     P15692             Alpha-lapachone  0.90  2.088932
211      P10275                 Citric acid  0.90  2.088932
...         ...                         ...   ...       ...
987      P42345           Limonene, (+/-)-   0.04 -2.700809
1339     P43405               DL-tryptophan  0.04 -2.700809
1337     P43405            L-phenylalanine   0.04 -2.700809
522      Q96PN6           Limonene, (+/-)-   0.02 -2.812198
1338     P43405  Trans-3-indoleacrylic acid  0.02 -2.812198

[2040 rows x 4 columns]

In [17]:
mean_value

0.5249313725490197

In [18]:
std_value

0.17955040356780566

In [19]:
filtered_df1 = df_sorted[df_sorted["Z_Score"] > 1.65]
filtered_df1

,UniProt ID,Drug,0,Z_Score
825,P32249,4-aminobenzoic acid,0.94,2.311711
1863,Q96DB2,Trans-3-indoleacrylic acid,0.94,2.311711
1260,P17612,4-aminobenzoic acid,0.92,2.200322
1612,P15692,Alpha-lapachone,0.90,2.088932
211,P10275,Citric acid,0.90,2.088932
...,...,...,...,...
1267,P17612,Alpha-lapachone,0.84,1.754764
1263,P17612,Trans-3-indoleacrylic acid,0.84,1.754764
478,Q13131,Pheophorbide a,0.84,1.754764
1496,P54646,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.84,1.754764
1719,P11217,Murraol,0.84,1.754764

In [20]:
filtered_df = df_sorted[df_sorted[0] > 0.9]
filtered_df

     UniProt ID                        Drug     0   Z_Score
825      P32249        4-aminobenzoic acid   0.94  2.311711
1863     Q96DB2  Trans-3-indoleacrylic acid  0.94  2.311711
1260     P17612        4-aminobenzoic acid   0.92  2.200322

In [21]:
df_sorted1 = result.sort_values(by=0, ascending=False)
df_sorted1 = df_sorted1.head(10)
df_sorted1

     UniProt ID                        Drug     0
825      P32249        4-aminobenzoic acid   0.94
1863     Q96DB2  Trans-3-indoleacrylic acid  0.94
1260     P17612        4-aminobenzoic acid   0.92
1612     P15692             Alpha-lapachone  0.90
211      P10275                 Citric acid  0.90
1        O15379                 Citric acid  0.90
1268     P17612              Hainanmurpanin  0.90
1272     P17612           Limonene, (+/-)-   0.90
1741     P21554                 Citric acid  0.90
204      Q05469                     Murraol  0.90

In [22]:
from scipy.stats import norm
# p-value untuk one-tailed (right)
df_sorted['p_value'] = 1 - norm.cdf(df_sorted['Z_Score'])

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted

     UniProt ID                        Drug     0   Z_Score   p_value
825      P32249        4-aminobenzoic acid   0.94  2.311711  0.010397
1863     Q96DB2  Trans-3-indoleacrylic acid  0.94  2.311711  0.010397
1260     P17612        4-aminobenzoic acid   0.92  2.200322  0.013892
1612     P15692             Alpha-lapachone  0.90  2.088932  0.018357
211      P10275                 Citric acid  0.90  2.088932  0.018357
...         ...                         ...   ...       ...       ...
987      P42345           Limonene, (+/-)-   0.04 -2.700809  0.996541
1339     P43405               DL-tryptophan  0.04 -2.700809  0.996541
1337     P43405            L-phenylalanine   0.04 -2.700809  0.996541
522      Q96PN6           Limonene, (+/-)-   0.02 -2.812198  0.997540
1338     P43405  Trans-3-indoleacrylic acid  0.02 -2.812198  0.997540

[2040 rows x 5 columns]

In [59]:
p_value = df_sorted[df_sorted["p_value"] < 0.05 ]
p_value

,UniProt ID,Drug,0,Z_Score,p_value
825,P32249,4-aminobenzoic acid,0.94,2.311711,0.010397
1863,Q96DB2,Trans-3-indoleacrylic acid,0.94,2.311711,0.010397
1260,P17612,4-aminobenzoic acid,0.92,2.200322,0.013892
1612,P15692,Alpha-lapachone,0.90,2.088932,0.018357
211,P10275,Citric acid,0.90,2.088932,0.018357
...,...,...,...,...,...
1267,P17612,Alpha-lapachone,0.84,1.754764,0.039650
1263,P17612,Trans-3-indoleacrylic acid,0.84,1.754764,0.039650
478,Q13131,Pheophorbide a,0.84,1.754764,0.039650
1496,P54646,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.84,1.754764,0.039650
1719,P11217,Murraol,0.84,1.754764,0.039650

In [60]:
p_value.shape

(68, 5)

In [24]:
p_value.to_csv('../../data/5-prediction/output/rf_predict_result.csv', index=False)

### Prediksi menggunakan Model XGBoost

In [25]:
model_xgb = load('../../data/4-modelling/result/bindingdb/AAIndex-Morgan/best_model_xgboost.joblib')

In [26]:
print(type(model_xgb))

<class 'xgboost.sklearn.XGBClassifier'>

In [27]:
hasil_prediksi1 = model_xgb.predict(testing_dff)
hasil_prediksi1

array([1, 1, 1, ..., 0, 1, 1])

In [28]:
proba1 = model_xgb.predict_proba(testing_dff)
proba1

array([[0.36153936, 0.63846064],
       [0.11955988, 0.8804401 ],
       [0.113047  , 0.886953  ],
       ...,
       [0.72204113, 0.2779589 ],
       [0.31227267, 0.68772733],
       [0.17258984, 0.82741016]], dtype=float32)

In [29]:
# Menggunakan .predict_proba() untuk mendapatkan probabilitas prediksi
y_proba_xgb = model_xgb.predict_proba(testing_dff)[:, 1]  # Probabilitas untuk kelas 1

# Menetapkan threshold 0.9 untuk prediksi kelas 1
threshold = 0.95
y_pred_custom = (y_proba_xgb >= threshold).astype(int)

print("Probabilitas prediksi untuk kelas 1:", y_proba_xgb)
print("Prediksi dengan threshold 0.8:", y_pred_custom)

Probabilitas prediksi untuk kelas 1: [0.63846064 0.8804401  0.886953   ... 0.2779589  0.68772733 0.82741016]
Prediksi dengan threshold 0.8: [0 0 0 ... 0 0 0]

In [30]:
hasil_xgb = pd.DataFrame(y_proba_xgb)
hasil_xgb

             0
0     0.638461
1     0.880440
2     0.886953
3     0.614259
4     0.851092
...        ...
2035  0.798571
2036  0.681131
2037  0.277959
2038  0.687727
2039  0.827410

[2040 rows x 1 columns]

In [31]:
result1 = pd.concat([inter_df, hasil_xgb], axis=1)
result1

     UniProt ID                                               Drug         0
0        O15379                               4-aminobenzoic acid   0.638461
1        O15379                                        Citric acid  0.880440
2        O15379                                   L-phenylalanine   0.886953
3        O15379                         Trans-3-indoleacrylic acid  0.614259
4        O15379                                      DL-tryptophan  0.851092
...         ...                                                ...       ...
2035     Q7Z4H4                                        Murralongin  0.798571
2036     Q7Z4H4  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...  0.681131
2037     Q7Z4H4                                  Limonene, (+/-)-   0.277959
2038     Q7Z4H4                                     Pheophorbide a  0.687727
2039     Q7Z4H4                                          SB236057   0.827410

[2040 rows x 3 columns]

In [32]:
df_sorted1 = result1.sort_values(by=0, ascending=False)
# df_sorted1 = df_sorted.head(10)
df_sorted1

     UniProt ID                                               Drug         0
583      P10828                                     Pheophorbide a  0.998064
463      Q16665                                     Pheophorbide a  0.996897
1614     P15692                                            Murraol  0.996689
1123     Q05513                                     Pheophorbide a  0.996571
253      P37231                                     Pheophorbide a  0.996172
...         ...                                                ...       ...
1181     Q9NZQ7  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...  0.014755
1346     P43405  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...  0.013892
1347     P43405                                  Limonene, (+/-)-   0.013491
1437     P08473                                  Limonene, (+/-)-   0.011411
627      Q13464                                  Limonene, (+/-)-   0.007315

[2040 rows x 3 columns]

In [33]:
filter1_df1 = df_sorted1[df_sorted1[0] > 0.95]
filter1_df1

     UniProt ID              Drug         0
583      P10828    Pheophorbide a  0.998064
463      Q16665    Pheophorbide a  0.996897
1614     P15692           Murraol  0.996689
1123     Q05513    Pheophorbide a  0.996571
253      P37231    Pheophorbide a  0.996172
...         ...               ...       ...
2012     Q9H093  L-phenylalanine   0.950816
868      O15294    Pheophorbide a  0.950424
1688     P30559    Hainanmurpanin  0.950388
1289     P27986         SB236057   0.950346
591      P61073       Murrangatin  0.950014

[178 rows x 3 columns]

In [34]:
# Membuat distribusi normal dari kolom
# Kita melakukan standarisasi nilai menjadi distribusi normal dengan mean 0 dan std 1
mean_value_xgb = df_sorted1[0].mean()
std_value_xgb = df_sorted1[0].std()
df_sorted1['Z_Score'] = (df_sorted1[0] - mean_value_xgb) / std_value_xgb

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted1

,UniProt ID,Drug,0,Z_Score
583,P10828,Pheophorbide a,0.998064,1.359777
463,Q16665,Pheophorbide a,0.996897,1.355389
1614,P15692,Murraol,0.996689,1.354607
1123,Q05513,Pheophorbide a,0.996571,1.354162
253,P37231,Pheophorbide a,0.996172,1.352665
...,...,...,...,...
1181,Q9NZQ7,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.014755,-2.336824
1346,P43405,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.013892,-2.340067
1347,P43405,"Limonene, (+/-)-",0.013491,-2.341574
1437,P08473,"Limonene, (+/-)-",0.011411,-2.349397
627,Q13464,"Limonene, (+/-)-",0.007315,-2.364792

In [35]:
mean_value_xgb

0.6363586

In [36]:
std_value_xgb

0.26600358

In [38]:
from scipy.stats import norm
# p-value untuk one-tailed (right)
df_sorted1['p_value'] = 1 - norm.cdf(df_sorted1['Z_Score'])

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted1

,UniProt ID,Drug,0,Z_Score,p_value
583,P10828,Pheophorbide a,0.998064,1.359777,0.086950
463,Q16665,Pheophorbide a,0.996897,1.355389,0.087647
1614,P15692,Murraol,0.996689,1.354607,0.087771
1123,Q05513,Pheophorbide a,0.996571,1.354162,0.087842
253,P37231,Pheophorbide a,0.996172,1.352665,0.088081
...,...,...,...,...,...
1181,Q9NZQ7,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.014755,-2.336824,0.990276
1346,P43405,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.013892,-2.340067,0.990360
1347,P43405,"Limonene, (+/-)-",0.013491,-2.341574,0.990399
1437,P08473,"Limonene, (+/-)-",0.011411,-2.349397,0.990598
627,Q13464,"Limonene, (+/-)-",0.007315,-2.364792,0.990980

In [39]:
p_value1 = df_sorted1[df_sorted1["p_value"] < 0.05 ]
p_value1

Empty DataFrame
Columns: [UniProt ID, Drug, 0, Z_Score, p_value]
Index: []

In [40]:
p_value1.to_csv('../../data/5-prediction/output/xgboost_predict_result.csv', index=False)

### Prediksi menggunakan Model MLP

In [41]:
model_mlp = load('../../data/4-modelling/result/bindingdb/AAIndex-Morgan/best_model_mlp.joblib')
print(model_mlp)

MLPClassifier(activation='tanh', alpha=0.001, random_state=42)

In [42]:
print(type(model_mlp))

<class 'sklearn.neural_network._multilayer_perceptron.MLPClassifier'>

In [43]:
hasil_prediksi2 = model_mlp.predict(testing_dff)
hasil_prediksi2

array([1, 1, 1, ..., 0, 1, 0])

In [44]:
proba2 = model_mlp.predict_proba(testing_dff)
proba2

array([[0.32924106, 0.67075894],
       [0.00865167, 0.99134833],
       [0.11494078, 0.88505922],
       ...,
       [0.93537805, 0.06462195],
       [0.03408268, 0.96591732],
       [0.63240945, 0.36759055]])

In [45]:
# Menggunakan .predict_proba() untuk mendapatkan probabilitas prediksi
y_proba_mlp = model_mlp.predict_proba(testing_dff)[:, 1]  # Probabilitas untuk kelas 1

# Menetapkan threshold 0.9 untuk prediksi kelas 1
threshold = 0.95
y_pred_custom = (y_proba_mlp >= threshold).astype(int)

print("Probabilitas prediksi untuk kelas 1:", y_proba_mlp)
print("Prediksi dengan threshold 0.8:", y_pred_custom)

Probabilitas prediksi untuk kelas 1: [0.67075894 0.99134833 0.88505922 ... 0.06462195 0.96591732 0.36759055]
Prediksi dengan threshold 0.8: [0 1 0 ... 0 1 0]

In [46]:
hasil_mlp = pd.DataFrame(y_proba_mlp)
hasil_mlp

             0
0     0.670759
1     0.991348
2     0.885059
3     0.379700
4     0.459804
...        ...
2035  0.138098
2036  0.059777
2037  0.064622
2038  0.965917
2039  0.367591

[2040 rows x 1 columns]

In [47]:
result2 = pd.concat([inter_df, hasil_mlp], axis=1)
result2

     UniProt ID                                               Drug         0
0        O15379                               4-aminobenzoic acid   0.670759
1        O15379                                        Citric acid  0.991348
2        O15379                                   L-phenylalanine   0.885059
3        O15379                         Trans-3-indoleacrylic acid  0.379700
4        O15379                                      DL-tryptophan  0.459804
...         ...                                                ...       ...
2035     Q7Z4H4                                        Murralongin  0.138098
2036     Q7Z4H4  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...  0.059777
2037     Q7Z4H4                                  Limonene, (+/-)-   0.064622
2038     Q7Z4H4                                     Pheophorbide a  0.965917
2039     Q7Z4H4                                          SB236057   0.367591

[2040 rows x 3 columns]

In [48]:
df_sorted2 = result2.sort_values(by=0, ascending=False)
# df_sorted2 = df_sorted.head(10)
df_sorted2

     UniProt ID                                               Drug         0
1228     P08069                                     Pheophorbide a  1.000000
1498     P54646                                     Pheophorbide a  1.000000
58       P06213                                     Pheophorbide a  0.999999
809      P27815                                          SB236057   0.999998
2023     Q9H093                                     Pheophorbide a  0.999997
...         ...                                                ...       ...
987      P42345                                  Limonene, (+/-)-   0.000003
1347     P43405                                  Limonene, (+/-)-   0.000003
1338     P43405                         Trans-3-indoleacrylic acid  0.000003
1341     P43405                                        Murrangatin  0.000003
1346     P43405  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...  0.000001

[2040 rows x 3 columns]

In [49]:
filter1_df2 = df_sorted2[df_sorted2[0] > 0.95]
filter1_df2

     UniProt ID                  Drug         0
1228     P08069        Pheophorbide a  1.000000
1498     P54646        Pheophorbide a  1.000000
58       P06213        Pheophorbide a  0.999999
809      P27815             SB236057   0.999998
2023     Q9H093        Pheophorbide a  0.999997
...         ...                   ...       ...
1769     P08908             SB236057   0.951212
706      Q9Y478           Citric acid  0.951158
730      P23975           Murralongin  0.951114
885      Q07869  4-aminobenzoic acid   0.950633
774      P43115               Murraol  0.950305

[827 rows x 3 columns]

In [50]:
# Membuat distribusi normal dari kolom
# Kita melakukan standarisasi nilai menjadi distribusi normal dengan mean 0 dan std 1
mean_value_mlp = df_sorted2[0].mean()
std_value_mlp = df_sorted2[0].std()
df_sorted2['Z_Score'] = (df_sorted2[0] - mean_value_mlp) / std_value_mlp

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted2

,UniProt ID,Drug,0,Z_Score
1228,P08069,Pheophorbide a,1.000000,0.846170
1498,P54646,Pheophorbide a,1.000000,0.846169
58,P06213,Pheophorbide a,0.999999,0.846168
809,P27815,SB236057,0.999998,0.846166
2023,Q9H093,Pheophorbide a,0.999997,0.846163
...,...,...,...,...
987,P42345,"Limonene, (+/-)-",0.000003,-1.943295
1347,P43405,"Limonene, (+/-)-",0.000003,-1.943295
1338,P43405,Trans-3-indoleacrylic acid,0.000003,-1.943295
1341,P43405,Murrangatin,0.000003,-1.943296
1346,P43405,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.000001,-1.943300

In [51]:
from scipy.stats import norm
# p-value untuk one-tailed (right)
df_sorted2['p_value'] = 1 - norm.cdf(df_sorted2['Z_Score'])

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted2

,UniProt ID,Drug,0,Z_Score,p_value
1228,P08069,Pheophorbide a,1.000000,0.846170,0.198729
1498,P54646,Pheophorbide a,1.000000,0.846169,0.198729
58,P06213,Pheophorbide a,0.999999,0.846168,0.198729
809,P27815,SB236057,0.999998,0.846166,0.198730
2023,Q9H093,Pheophorbide a,0.999997,0.846163,0.198731
...,...,...,...,...,...
987,P42345,"Limonene, (+/-)-",0.000003,-1.943295,0.974010
1347,P43405,"Limonene, (+/-)-",0.000003,-1.943295,0.974010
1338,P43405,Trans-3-indoleacrylic acid,0.000003,-1.943295,0.974010
1341,P43405,Murrangatin,0.000003,-1.943296,0.974010
1346,P43405,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.000001,-1.943300,0.974010

In [52]:
mean_value_mlp

0.6966558605829876

In [53]:
std_value_mlp

0.35849055901918503

In [73]:
p_value2 = df_sorted2[df_sorted2["p_value"] < 0.05 ]
p_value2

Empty DataFrame
Columns: [UniProt ID, Drug, 0, Z_Score, p_value]
Index: []

In [74]:
p_value2.to_csv('../../data/5-prediction/output/mlp_predict_result.csv', index=False)

### Nama Protein

In [64]:
fasta_df = pd.read_csv('../../data/1-preparation/prot/protein.csv')
fasta_df = fasta_df.drop_duplicates(subset='UniProt ID')
fasta_df = fasta_df.drop(columns=['FASTA Sequence'])
fasta_df = fasta_df.reset_index(drop=True)
fasta_df

    Gene Symbol UniProt ID                                       Protein Name
0          UCP1     P25874       Mitochondrial brown fat uncoupling protein 1
1      PPARGC1A     Q9UBK2  Peroxisome proliferator-activated receptor gam...
2         HDAC3     O15379                              Histone deacetylase 3
3      PPARGC1B     Q86YN6  Peroxisome proliferator-activated receptor gam...
4          SGSH     P51688                N-sulphoglucosamine sulphohydrolase
..          ...        ...                                                ...
460      TM4SF5     O14894                 Transmembrane 4 L6 family member 5
461       LPIN3     Q9BQK8                    Phosphatidate phosphatase LPIN3
462      ZC3H10     Q96K80      Zinc finger CCCH domain-containing protein 10
463        PRLH     P81277                        Prolactin-releasing peptide
464         TRA     P0DSE1            M1-specific T cell receptor alpha chain

[465 rows x 3 columns]

In [65]:
p_value

,UniProt ID,Drug,0,Z_Score,p_value
825,P32249,4-aminobenzoic acid,0.94,2.311711,0.010397
1863,Q96DB2,Trans-3-indoleacrylic acid,0.94,2.311711,0.010397
1260,P17612,4-aminobenzoic acid,0.92,2.200322,0.013892
1612,P15692,Alpha-lapachone,0.90,2.088932,0.018357
211,P10275,Citric acid,0.90,2.088932,0.018357
...,...,...,...,...,...
1267,P17612,Alpha-lapachone,0.84,1.754764,0.039650
1263,P17612,Trans-3-indoleacrylic acid,0.84,1.754764,0.039650
478,Q13131,Pheophorbide a,0.84,1.754764,0.039650
1496,P54646,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.84,1.754764,0.039650
1719,P11217,Murraol,0.84,1.754764,0.039650

In [66]:
rf_pvalue = p_value.merge(fasta_df, on='UniProt ID', how='left')
rf_pvalue

,UniProt ID,Drug,0,Z_Score,p_value,Gene Symbol,Protein Name
0,P32249,4-aminobenzoic acid,0.94,2.311711,0.010397,GPR183,G-protein coupled receptor 183
1,Q96DB2,Trans-3-indoleacrylic acid,0.94,2.311711,0.010397,HDAC11,Histone deacetylase 11
2,P17612,4-aminobenzoic acid,0.92,2.200322,0.013892,PRKACA,cAMP-dependent protein kinase catalytic subuni...
3,P15692,Alpha-lapachone,0.90,2.088932,0.018357,VEGFA,"Vascular endothelial growth factor A, long form"
4,P10275,Citric acid,0.90,2.088932,0.018357,AR,Androgen receptor
...,...,...,...,...,...,...,...
63,P17612,Alpha-lapachone,0.84,1.754764,0.039650,PRKACA,cAMP-dependent protein kinase catalytic subuni...
64,P17612,Trans-3-indoleacrylic acid,0.84,1.754764,0.039650,PRKACA,cAMP-dependent protein kinase catalytic subuni...
65,Q13131,Pheophorbide a,0.84,1.754764,0.039650,PRKAA1,5'-AMP-activated protein kinase catalytic subu...
66,P54646,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.84,1.754764,0.039650,PRKAA2,5'-AMP-activated protein kinase catalytic subu...
67,P11217,Murraol,0.84,1.754764,0.039650,PYGM,"Glycogen phosphorylase, muscle form"

In [67]:
tes = rf_pvalue.drop(columns=['Drug', 0, 'Z_Score', 'p_value'])
tes

   UniProt ID Gene Symbol                                       Protein Name
0      P32249      GPR183                     G-protein coupled receptor 183
1      Q96DB2      HDAC11                             Histone deacetylase 11
2      P17612      PRKACA  cAMP-dependent protein kinase catalytic subuni...
3      P15692       VEGFA    Vascular endothelial growth factor A, long form
4      P10275          AR                                  Androgen receptor
..        ...         ...                                                ...
63     P17612      PRKACA  cAMP-dependent protein kinase catalytic subuni...
64     P17612      PRKACA  cAMP-dependent protein kinase catalytic subuni...
65     Q13131      PRKAA1  5'-AMP-activated protein kinase catalytic subu...
66     P54646      PRKAA2  5'-AMP-activated protein kinase catalytic subu...
67     P11217        PYGM                Glycogen phosphorylase, muscle form

[68 rows x 3 columns]

In [68]:
tes2 = rf_pvalue.drop(columns=['UniProt ID', 'Gene Symbol', 'Protein Name'])
tes2

,Drug,0,Z_Score,p_value
0,4-aminobenzoic acid,0.94,2.311711,0.010397
1,Trans-3-indoleacrylic acid,0.94,2.311711,0.010397
2,4-aminobenzoic acid,0.92,2.200322,0.013892
3,Alpha-lapachone,0.90,2.088932,0.018357
4,Citric acid,0.90,2.088932,0.018357
...,...,...,...,...
63,Alpha-lapachone,0.84,1.754764,0.039650
64,Trans-3-indoleacrylic acid,0.84,1.754764,0.039650
65,Pheophorbide a,0.84,1.754764,0.039650
66,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.84,1.754764,0.039650
67,Murraol,0.84,1.754764,0.039650

In [72]:
result = pd.concat([tes, tes2], axis=1)
result.rename(columns={0:'Prob Score', 'p_value':'P Value'}, inplace=True)
result

,UniProt ID,Gene Symbol,Protein Name,Drug,Prob Score,Z_Score,P Value
0,P32249,GPR183,G-protein coupled receptor 183,4-aminobenzoic acid,0.94,2.311711,0.010397
1,Q96DB2,HDAC11,Histone deacetylase 11,Trans-3-indoleacrylic acid,0.94,2.311711,0.010397
2,P17612,PRKACA,cAMP-dependent protein kinase catalytic subuni...,4-aminobenzoic acid,0.92,2.200322,0.013892
3,P15692,VEGFA,"Vascular endothelial growth factor A, long form",Alpha-lapachone,0.90,2.088932,0.018357
4,P10275,AR,Androgen receptor,Citric acid,0.90,2.088932,0.018357
...,...,...,...,...,...,...,...
63,P17612,PRKACA,cAMP-dependent protein kinase catalytic subuni...,Alpha-lapachone,0.84,1.754764,0.039650
64,P17612,PRKACA,cAMP-dependent protein kinase catalytic subuni...,Trans-3-indoleacrylic acid,0.84,1.754764,0.039650
65,Q13131,PRKAA1,5'-AMP-activated protein kinase catalytic subu...,Pheophorbide a,0.84,1.754764,0.039650
66,P54646,PRKAA2,5'-AMP-activated protein kinase catalytic subu...,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.84,1.754764,0.039650
67,P11217,PYGM,"Glycogen phosphorylase, muscle form",Murraol,0.84,1.754764,0.039650

In [75]:
result.to_csv('../../data/5-prediction/output/predict_done.csv', index=False)

### Jumlah senyawa dan jumlah protein

In [76]:
import pandas as pd

In [77]:
hasil = pd.read_csv('../../data/5-prediction/output/predict_done.csv')
hasil

,UniProt ID,Gene Symbol,Protein Name,Drug,Prob Score,Z_Score,P Value
0,P32249,GPR183,G-protein coupled receptor 183,4-aminobenzoic acid,0.94,2.311711,0.010397
1,Q96DB2,HDAC11,Histone deacetylase 11,Trans-3-indoleacrylic acid,0.94,2.311711,0.010397
2,P17612,PRKACA,cAMP-dependent protein kinase catalytic subuni...,4-aminobenzoic acid,0.92,2.200322,0.013892
3,P15692,VEGFA,"Vascular endothelial growth factor A, long form",Alpha-lapachone,0.90,2.088932,0.018357
4,P10275,AR,Androgen receptor,Citric acid,0.90,2.088932,0.018357
...,...,...,...,...,...,...,...
63,P17612,PRKACA,cAMP-dependent protein kinase catalytic subuni...,Alpha-lapachone,0.84,1.754764,0.039650
64,P17612,PRKACA,cAMP-dependent protein kinase catalytic subuni...,Trans-3-indoleacrylic acid,0.84,1.754764,0.039650
65,Q13131,PRKAA1,5'-AMP-activated protein kinase catalytic subu...,Pheophorbide a,0.84,1.754764,0.039650
66,P54646,PRKAA2,5'-AMP-activated protein kinase catalytic subu...,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.84,1.754764,0.039650
67,P11217,PYGM,"Glycogen phosphorylase, muscle form",Murraol,0.84,1.754764,0.039650

In [90]:
# Menghitung jumlah senyawa dengan nama yang sama
drug_counts = hasil['Drug'].value_counts().reset_index()
drug_counts.columns = ['Drug', 'Count']

# Menggabungkan hasil jumlah ke DataFrame asli
senyawa = hasil.merge(drug_counts, on='Drug')

In [91]:
senyawa = senyawa.drop_duplicates(subset='Drug')
senyawa

,UniProt ID,Gene Symbol,Protein Name,Drug,Prob Score,Z_Score,P Value,Count
0,P32249,GPR183,G-protein coupled receptor 183,4-aminobenzoic acid,0.94,2.311711,0.010397,9
1,Q96DB2,HDAC11,Histone deacetylase 11,Trans-3-indoleacrylic acid,0.94,2.311711,0.010397,3
3,P15692,VEGFA,"Vascular endothelial growth factor A, long form",Alpha-lapachone,0.90,2.088932,0.018357,3
4,P10275,AR,Androgen receptor,Citric acid,0.90,2.088932,0.018357,12
6,P17612,PRKACA,cAMP-dependent protein kinase catalytic subuni...,Hainanmurpanin,0.90,2.088932,0.018357,6
7,P17612,PRKACA,cAMP-dependent protein kinase catalytic subuni...,"Limonene, (+/-)-",0.90,2.088932,0.018357,3
9,Q05469,LIPE,Hormone-sensitive lipase,Murraol,0.90,2.088932,0.018357,7
12,Q05469,LIPE,Hormone-sensitive lipase,Murrangatin,0.90,2.088932,0.018357,3
13,P61073,CXCR4,C-X-C chemokine receptor type 4,L-phenylalanine,0.90,2.088932,0.018357,9
21,P35354,PTGS2,Prostaglandin G/H synthase 2,DL-tryptophan,0.88,1.977543,0.023990,3
22,Q16665,HIF1A,Hypoxia-inducible factor 1-alpha,4-O-feruloyl-D-quinic acid,0.88,1.977543,0.023990,3
30,P15692,VEGFA,"Vascular endothelial growth factor A, long form",Murralongin,0.88,1.977543,0.023990,3
51,Q99814,EPAS1,Endothelial PAS domain-containing protein 1,Pheophorbide a,0.84,1.754764,0.039650,2
53,Q99814,EPAS1,Endothelial PAS domain-containing protein 1,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...",0.84,1.754764,0.039650,2

In [82]:
senyawa.to_csv('../../data/5-prediction/output/predict_SenyawaCount.csv', index=False)

In [37]:
result_rf = pd.read_csv('./predict_rf.csv') 
result_rf

     uniprot_id                     Senyawa         0   Z_Score
0        P28223                 Citric acid  0.987333  1.820573
1        P49768                 Citric acid  0.985417  1.806587
2        P49768  4-O-feruloyl-D-quinic acid  0.982069  1.782162
3        P05106                 Citric acid  0.981821  1.780352
4        P14416                 Citric acid  0.980429  1.770189
...         ...                         ...       ...       ...
3730     O43521                 Murralongin  0.194894 -3.961865
3731     O43521  Trans-3-indoleacrylic acid  0.181222 -4.061630
3732     O43521            L-phenylalanine   0.171693 -4.131165
3733     O43521                 Citric acid  0.157949 -4.231457
3734     O43521        4-aminobenzoic acid   0.110333 -4.578907

[3735 rows x 4 columns]

In [35]:
df_sorted1 #XGBoost

     uniprot_id               Senyawa         0   Z_Score
2477     P49768      L-phenylalanine   0.999287  0.577825
3182     P00338      L-phenylalanine   0.999257  0.577633
2404     P27338         DL-tryptophan  0.999092  0.576553
1952     P13569      L-phenylalanine   0.999089  0.576536
2479     P49768         DL-tryptophan  0.999054  0.576305
...         ...                   ...       ...       ...
1980     P23443  4-aminobenzoic acid   0.048494 -5.621172
1990     P23443           Murralongin  0.044965 -5.644180
1989     P23443               Murraol  0.032541 -5.725183
1992     P23443     Limonene, (+/-)-   0.030858 -5.736153
1987     P23443       Alpha-lapachone  0.026509 -5.764510

[3735 rows x 4 columns]

In [36]:
df_sorted2 #MLP

     uniprot_id               Senyawa         0   Z_Score
89       P05121             SB236057   1.000000  0.336073
524      P42345             SB236057   1.000000  0.336073
82       P05121       Alpha-lapachone  1.000000  0.336073
77       P05121      L-phenylalanine   1.000000  0.336073
3098     P78527        Hainanmurpanin  1.000000  0.336073
...         ...                   ...       ...       ...
2835     Q07820  4-aminobenzoic acid   0.000195 -4.282993
2326     O14965           Citric acid  0.000145 -4.283222
15       P04637  4-aminobenzoic acid   0.000125 -4.283314
2331     O14965           Murrangatin  0.000023 -4.283786
3270     P06730  4-aminobenzoic acid   0.000004 -4.283873

[3735 rows x 4 columns]