In [1]:
import pandas as pd
from joblib import load

In [2]:
testing_df = pd.read_csv('../../../data/murraya/aaindex_morgan_murraya.csv') 
testing_df

,uniprot_id,ANDN920101,ARGP820101,ARGP820102,ARGP820103,BEGF750101,BEGF750102,BEGF750103,BHAR880101,BIGC670101,...,1015,1016,1017,1018,1019,1020,1021,1022,1023,Senyawa
0,P05231,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,...,0,0,0,0,0,0,0,0,0,4-aminobenzoic acid
1,P05231,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,...,0,0,0,0,0,0,0,0,0,Citric acid
2,P05231,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,...,0,0,1,0,0,0,0,0,0,L-phenylalanine
3,P05231,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,...,0,0,0,0,0,0,0,0,0,Trans-3-indoleacrylic acid
4,P05231,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,...,0,0,0,0,0,0,0,0,0,DL-tryptophan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3730,P25098,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,...,0,0,1,0,0,0,0,0,0,Murralongin
3731,P25098,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,...,0,0,0,0,1,0,0,0,0,"(1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(..."
3732,P25098,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,...,0,0,1,0,1,1,0,1,0,"Limonene, (+/-)-"
3733,P25098,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,...,0,0,0,0,1,0,0,0,0,Pheophorbide a
3734,P25098,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,...,0,0,0,0,0,0,0,0,0,SB236057

In [3]:
inter_df = testing_df[['uniprot_id','Senyawa']]
inter_df

     uniprot_id                                            Senyawa
0        P05231                               4-aminobenzoic acid
1        P05231                                        Citric acid
2        P05231                                   L-phenylalanine
3        P05231                         Trans-3-indoleacrylic acid
4        P05231                                      DL-tryptophan
...         ...                                                ...
3730     P25098                                        Murralongin
3731     P25098  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...
3732     P25098                                  Limonene, (+/-)-
3733     P25098                                     Pheophorbide a
3734     P25098                                          SB236057

[3735 rows x 2 columns]

In [4]:
testing_dff = testing_df.drop(columns=['uniprot_id','Senyawa'])
testing_dff

,ANDN920101,ARGP820101,ARGP820102,ARGP820103,BEGF750101,BEGF750102,BEGF750103,BHAR880101,BIGC670101,BIOV880101,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
0,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,-0.392525,...,0,0,0,0,0,0,0,0,0,0
1,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,-0.392525,...,0,0,0,0,0,0,0,0,0,0
2,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,-0.392525,...,0,0,0,1,0,0,0,0,0,0
3,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,-0.392525,...,0,0,0,0,0,0,0,0,0,0
4,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,-0.392525,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3730,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,-0.148100,...,0,0,0,1,0,0,0,0,0,0
3731,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,-0.148100,...,0,0,0,0,0,1,0,0,0,0
3732,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,-0.148100,...,0,0,0,1,0,1,1,0,1,0
3733,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,-0.148100,...,0,0,0,0,0,1,0,0,0,0
3734,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,-0.148100,...,0,0,0,0,0,0,0,0,0,0

In [5]:
testing_dff.columns = range(len(testing_dff.columns))
testing_dff

,0,1,2,3,4,5,6,7,8,9,...,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576
0,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,-0.392525,...,0,0,0,0,0,0,0,0,0,0
1,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,-0.392525,...,0,0,0,0,0,0,0,0,0,0
2,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,-0.392525,...,0,0,0,1,0,0,0,0,0,0
3,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,-0.392525,...,0,0,0,0,0,0,0,0,0,0
4,0.547860,-0.806375,1.122797,0.993967,0.901913,-0.407392,-1.123467,-0.406683,0.037629,-0.392525,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3730,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,-0.148100,...,0,0,0,1,0,0,0,0,0,0
3731,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,-0.148100,...,0,0,0,0,0,1,0,0,0,0
3732,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,-0.148100,...,0,0,0,1,0,1,1,0,1,0
3733,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,-0.148100,...,0,0,0,0,0,1,0,0,0,0
3734,0.169068,0.359840,0.035393,0.084718,0.849163,0.020692,-0.421114,-0.208553,1.166114,-0.148100,...,0,0,0,0,0,0,0,0,0,0

### Prediksi menggunakan Model Random Forest

In [6]:
model = load('../Modelling/random_forest_am.joblib')

In [7]:
print(type(model))

<class 'sklearn.ensemble._forest.RandomForestClassifier'>

In [8]:
hasil_prediksi = model.predict(testing_dff)
hasil_prediksi

array([1., 1., 1., ..., 1., 1., 1.])

In [9]:
proba = model.predict_proba(testing_dff)
proba

array([[0.22962837, 0.77037163],
       [0.16027042, 0.83972958],
       [0.24363176, 0.75636824],
       ...,
       [0.31541811, 0.68458189],
       [0.39332133, 0.60667867],
       [0.32050992, 0.67949008]])

In [10]:
# Menggunakan .predict_proba() untuk mendapatkan probabilitas prediksi
y_proba = model.predict_proba(testing_dff)[:, 1]  # Probabilitas untuk kelas 1

# Menetapkan threshold 0.9 untuk prediksi kelas 1
threshold = 0.95
y_pred_custom = (y_proba >= threshold).astype(int)

print("Probabilitas prediksi untuk kelas 1:", y_proba)
print("Prediksi dengan threshold 0.8:", y_pred_custom)

Probabilitas prediksi untuk kelas 1: [0.77037163 0.83972958 0.75636824 ... 0.68458189 0.60667867 0.67949008]
Prediksi dengan threshold 0.8: [0 0 0 ... 0 0 0]

In [11]:
hasil = pd.DataFrame(y_proba)
hasil

             0
0     0.770372
1     0.839730
2     0.756368
3     0.776057
4     0.728428
...        ...
3730  0.751353
3731  0.687566
3732  0.684582
3733  0.606679
3734  0.679490

[3735 rows x 1 columns]

In [12]:
result = pd.concat([inter_df, hasil], axis=1)
result

     uniprot_id                                            Senyawa         0
0        P05231                               4-aminobenzoic acid   0.770372
1        P05231                                        Citric acid  0.839730
2        P05231                                   L-phenylalanine   0.756368
3        P05231                         Trans-3-indoleacrylic acid  0.776057
4        P05231                                      DL-tryptophan  0.728428
...         ...                                                ...       ...
3730     P25098                                        Murralongin  0.751353
3731     P25098  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...  0.687566
3732     P25098                                  Limonene, (+/-)-   0.684582
3733     P25098                                     Pheophorbide a  0.606679
3734     P25098                                          SB236057   0.679490

[3735 rows x 3 columns]

In [13]:
hasil = pd.DataFrame(y_proba)
hasil

             0
0     0.770372
1     0.839730
2     0.756368
3     0.776057
4     0.728428
...        ...
3730  0.751353
3731  0.687566
3732  0.684582
3733  0.606679
3734  0.679490

[3735 rows x 1 columns]

In [14]:
hasil[0].value_counts()

0
0.941333    2
0.770372    1
0.814153    1
0.968528    1
0.945333    1
           ..
0.926706    1
0.913167    1
0.903194    1
0.838908    1
0.679490    1
Name: count, Length: 3734, dtype: int64

In [15]:
df_sorted = result.sort_values(by=0, ascending=False)
# df_sorted = df_sorted.head(10)
df_sorted

     uniprot_id                     Senyawa         0
2626     P28223                 Citric acid  0.987333
2476     P49768                 Citric acid  0.985417
2480     P49768  4-O-feruloyl-D-quinic acid  0.982069
2026     P05106                 Citric acid  0.981821
2686     P14416                 Citric acid  0.980429
...         ...                         ...       ...
3295     O43521                 Murralongin  0.194894
3288     O43521  Trans-3-indoleacrylic acid  0.181222
3287     O43521            L-phenylalanine   0.171693
3286     O43521                 Citric acid  0.157949
3285     O43521        4-aminobenzoic acid   0.110333

[3735 rows x 3 columns]

In [16]:
filter1_df = df_sorted[df_sorted[0] > 0.95]
filter1_df

     uniprot_id                     Senyawa         0
2626     P28223                 Citric acid  0.987333
2476     P49768                 Citric acid  0.985417
2480     P49768  4-O-feruloyl-D-quinic acid  0.982069
2026     P05106                 Citric acid  0.981821
2686     P14416                 Citric acid  0.980429
3080     Q8NER1  4-O-feruloyl-D-quinic acid  0.980083
2108     P24941              Hainanmurpanin  0.975123
2025     P05106        4-aminobenzoic acid   0.974833
2405     P27338  4-O-feruloyl-D-quinic acid  0.972917
3543     Q92769  Trans-3-indoleacrylic acid  0.972875
1868     P04798              Hainanmurpanin  0.972083
2688     P14416  Trans-3-indoleacrylic acid  0.971125
1126     Q16539                 Citric acid  0.970292
2105     P24941  4-O-feruloyl-D-quinic acid  0.970250
3545     Q92769  4-O-feruloyl-D-quinic acid  0.970042
1870     P04798                 Murralongin  0.969750
2110     P24941                 Murralongin  0.968893
2483     P49768              Hainanmurpanin  0.968528
2410     P27338                 Murralongin  0.967476
241      Q07869                 Citric acid  0.966740
2485     P49768                 Murralongin  0.966421
2627     P28223            L-phenylalanine   0.964738
2690     P14416  4-O-feruloyl-D-quinic acid  0.964560
3541     Q92769                 Citric acid  0.964313
2403     P27338  Trans-3-indoleacrylic acid  0.964000
3085     Q8NER1                 Murralongin  0.963369
151      P08253                 Citric acid  0.963333
2477     P49768            L-phenylalanine   0.962160
1366     P07550                 Citric acid  0.961167
2478     P49768  Trans-3-indoleacrylic acid  0.960750
2691     P14416                 Murrangatin  0.960083
2402     P27338            L-phenylalanine   0.960042
2694     P14416                     Murraol  0.959810
3083     Q8NER1              Hainanmurpanin  0.959524
211      P11511                 Citric acid  0.958405
2695     P14416                 Murralongin  0.957893
2027     P05106            L-phenylalanine   0.957719
2693     P14416              Hainanmurpanin  0.957329
2628     P28223  Trans-3-indoleacrylic acid  0.957012
2101     P24941                 Citric acid  0.956738
3550     Q92769                 Murralongin  0.956726
3302     P35372            L-phenylalanine   0.956369
3228     Q9UBN7  Trans-3-indoleacrylic acid  0.955401
571      P10275                 Citric acid  0.955250
3301     P35372                 Citric acid  0.954710
3061     P05089                 Citric acid  0.954681
2685     P14416        4-aminobenzoic acid   0.954539
2475     P49768        4-aminobenzoic acid   0.954486
1205     Q92731  4-O-feruloyl-D-quinic acid  0.954323
2673     Q13547  Trans-3-indoleacrylic acid  0.952366
3213     P56524  Trans-3-indoleacrylic acid  0.952277
2630     P28223  4-O-feruloyl-D-quinic acid  0.951639
108      P03372  Trans-3-indoleacrylic acid  0.950343

In [17]:

# Membuat distribusi normal dari kolom
# Kita melakukan standarisasi nilai menjadi distribusi normal dengan mean 0 dan std 1
mean_value = df_sorted[0].mean()
std_value = df_sorted[0].std()
df_sorted['Z_Score'] = (df_sorted[0] - mean_value) / std_value

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted

     uniprot_id                     Senyawa         0   Z_Score
2626     P28223                 Citric acid  0.987333  1.820573
2476     P49768                 Citric acid  0.985417  1.806587
2480     P49768  4-O-feruloyl-D-quinic acid  0.982069  1.782162
2026     P05106                 Citric acid  0.981821  1.780352
2686     P14416                 Citric acid  0.980429  1.770189
...         ...                         ...       ...       ...
3295     O43521                 Murralongin  0.194894 -3.961865
3288     O43521  Trans-3-indoleacrylic acid  0.181222 -4.061630
3287     O43521            L-phenylalanine   0.171693 -4.131165
3286     O43521                 Citric acid  0.157949 -4.231457
3285     O43521        4-aminobenzoic acid   0.110333 -4.578907

[3735 rows x 4 columns]

In [18]:
mean_value

0.7378376824730679

In [19]:
std_value

0.13704239010655456

In [20]:
filtered_df1 = df_sorted[df_sorted["Z_Score"] > 1.65]
filtered_df1

     uniprot_id                     Senyawa         0   Z_Score
2626     P28223                 Citric acid  0.987333  1.820573
2476     P49768                 Citric acid  0.985417  1.806587
2480     P49768  4-O-feruloyl-D-quinic acid  0.982069  1.782162
2026     P05106                 Citric acid  0.981821  1.780352
2686     P14416                 Citric acid  0.980429  1.770189
3080     Q8NER1  4-O-feruloyl-D-quinic acid  0.980083  1.767669
2108     P24941              Hainanmurpanin  0.975123  1.731474
2025     P05106        4-aminobenzoic acid   0.974833  1.729360
2405     P27338  4-O-feruloyl-D-quinic acid  0.972917  1.715374
3543     Q92769  Trans-3-indoleacrylic acid  0.972875  1.715070
1868     P04798              Hainanmurpanin  0.972083  1.709293
2688     P14416  Trans-3-indoleacrylic acid  0.971125  1.702300
1126     Q16539                 Citric acid  0.970292  1.696220
2105     P24941  4-O-feruloyl-D-quinic acid  0.970250  1.695916
3545     Q92769  4-O-feruloyl-D-quinic acid  0.970042  1.694395
1870     P04798                 Murralongin  0.969750  1.692267
2110     P24941                 Murralongin  0.968893  1.686012
2483     P49768              Hainanmurpanin  0.968528  1.683348
2410     P27338                 Murralongin  0.967476  1.675675
241      Q07869                 Citric acid  0.966740  1.670306
2485     P49768                 Murralongin  0.966421  1.667973
2627     P28223            L-phenylalanine   0.964738  1.655695
2690     P14416  4-O-feruloyl-D-quinic acid  0.964560  1.654392
3541     Q92769                 Citric acid  0.964313  1.652590
2403     P27338  Trans-3-indoleacrylic acid  0.964000  1.650309

In [21]:
filtered_df = df_sorted[df_sorted[0] > 0.9]
filtered_df

     uniprot_id                     Senyawa         0   Z_Score
2626     P28223                 Citric acid  0.987333  1.820573
2476     P49768                 Citric acid  0.985417  1.806587
2480     P49768  4-O-feruloyl-D-quinic acid  0.982069  1.782162
2026     P05106                 Citric acid  0.981821  1.780352
2686     P14416                 Citric acid  0.980429  1.770189
...         ...                         ...       ...       ...
1307     P35968            L-phenylalanine   0.900508  1.187008
3698     P41594              Hainanmurpanin  0.900417  1.186341
3318     P62942  Trans-3-indoleacrylic acid  0.900262  1.185211
1008     P00749  Trans-3-indoleacrylic acid  0.900065  1.183778
3098     P78527              Hainanmurpanin  0.900006  1.183344

[357 rows x 4 columns]

In [22]:
df_sorted1 = result.sort_values(by=0, ascending=False)
df_sorted1 = df_sorted1.head(10)
df_sorted1

     uniprot_id                     Senyawa         0
2626     P28223                 Citric acid  0.987333
2476     P49768                 Citric acid  0.985417
2480     P49768  4-O-feruloyl-D-quinic acid  0.982069
2026     P05106                 Citric acid  0.981821
2686     P14416                 Citric acid  0.980429
3080     Q8NER1  4-O-feruloyl-D-quinic acid  0.980083
2108     P24941              Hainanmurpanin  0.975123
2025     P05106        4-aminobenzoic acid   0.974833
2405     P27338  4-O-feruloyl-D-quinic acid  0.972917
3543     Q92769  Trans-3-indoleacrylic acid  0.972875

In [50]:
df_sorted.to_csv('./predict_rf.csv', index=False)

In [23]:
from scipy.stats import norm
# p-value untuk one-tailed (right)
df_sorted['p_value'] = 1 - norm.cdf(df_sorted['Z_Score'])

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted

     uniprot_id                     Senyawa         0   Z_Score   p_value
2626     P28223                 Citric acid  0.987333  1.820573  0.034336
2476     P49768                 Citric acid  0.985417  1.806587  0.035413
2480     P49768  4-O-feruloyl-D-quinic acid  0.982069  1.782162  0.037361
2026     P05106                 Citric acid  0.981821  1.780352  0.037509
2686     P14416                 Citric acid  0.980429  1.770189  0.038348
...         ...                         ...       ...       ...       ...
3295     O43521                 Murralongin  0.194894 -3.961865  0.999963
3288     O43521  Trans-3-indoleacrylic acid  0.181222 -4.061630  0.999976
3287     O43521            L-phenylalanine   0.171693 -4.131165  0.999982
3286     O43521                 Citric acid  0.157949 -4.231457  0.999988
3285     O43521        4-aminobenzoic acid   0.110333 -4.578907  0.999998

[3735 rows x 5 columns]

In [24]:
p_value = df_sorted[df_sorted["p_value"] < 0.05 ]
p_value

     uniprot_id                     Senyawa         0   Z_Score   p_value
2626     P28223                 Citric acid  0.987333  1.820573  0.034336
2476     P49768                 Citric acid  0.985417  1.806587  0.035413
2480     P49768  4-O-feruloyl-D-quinic acid  0.982069  1.782162  0.037361
2026     P05106                 Citric acid  0.981821  1.780352  0.037509
2686     P14416                 Citric acid  0.980429  1.770189  0.038348
3080     Q8NER1  4-O-feruloyl-D-quinic acid  0.980083  1.767669  0.038558
2108     P24941              Hainanmurpanin  0.975123  1.731474  0.041684
2025     P05106        4-aminobenzoic acid   0.974833  1.729360  0.041872
2405     P27338  4-O-feruloyl-D-quinic acid  0.972917  1.715374  0.043138
3543     Q92769  Trans-3-indoleacrylic acid  0.972875  1.715070  0.043166
1868     P04798              Hainanmurpanin  0.972083  1.709293  0.043698
2688     P14416  Trans-3-indoleacrylic acid  0.971125  1.702300  0.044350
1126     Q16539                 Citric acid  0.970292  1.696220  0.044922
2105     P24941  4-O-feruloyl-D-quinic acid  0.970250  1.695916  0.044951
3545     Q92769  4-O-feruloyl-D-quinic acid  0.970042  1.694395  0.045095
1870     P04798                 Murralongin  0.969750  1.692267  0.045298
2110     P24941                 Murralongin  0.968893  1.686012  0.045897
2483     P49768              Hainanmurpanin  0.968528  1.683348  0.046154
2410     P27338                 Murralongin  0.967476  1.675675  0.046901
241      Q07869                 Citric acid  0.966740  1.670306  0.047429
2485     P49768                 Murralongin  0.966421  1.667973  0.047661
2627     P28223            L-phenylalanine   0.964738  1.655695  0.048892
2690     P14416  4-O-feruloyl-D-quinic acid  0.964560  1.654392  0.049024
3541     Q92769                 Citric acid  0.964313  1.652590  0.049207
2403     P27338  Trans-3-indoleacrylic acid  0.964000  1.650309  0.049440
3085     Q8NER1                 Murralongin  0.963369  1.645705  0.049912
151      P08253                 Citric acid  0.963333  1.645445  0.049939

In [29]:
p_value.shape

(27, 5)

In [30]:
p_value.to_csv('./predict_rf_pvalue.csv', index=False)

### Prediksi menggunakan Model XGBoost

In [6]:
model_xgb = load('xgboost_am.joblib')

In [7]:
print(type(model_xgb))

<class 'xgboost.sklearn.XGBClassifier'>

In [8]:
hasil_prediksi1 = model_xgb.predict(testing_dff)
hasil_prediksi1

array([1, 1, 1, ..., 1, 1, 1])

In [9]:
proba1 = model_xgb.predict_proba(testing_dff)
proba1

array([[0.01286036, 0.98713964],
       [0.01552308, 0.9844769 ],
       [0.00307792, 0.9969221 ],
       ...,
       [0.01976043, 0.98023957],
       [0.2214824 , 0.7785176 ],
       [0.09907901, 0.900921  ]], dtype=float32)

In [10]:
# Menggunakan .predict_proba() untuk mendapatkan probabilitas prediksi
y_proba_xgb = model_xgb.predict_proba(testing_dff)[:, 1]  # Probabilitas untuk kelas 1

# Menetapkan threshold 0.9 untuk prediksi kelas 1
threshold = 0.95
y_pred_custom = (y_proba_xgb >= threshold).astype(int)

print("Probabilitas prediksi untuk kelas 1:", y_proba_xgb)
print("Prediksi dengan threshold 0.8:", y_pred_custom)

Probabilitas prediksi untuk kelas 1: [0.98713964 0.9844769  0.9969221  ... 0.98023957 0.7785176  0.900921  ]
Prediksi dengan threshold 0.8: [1 1 1 ... 1 0 0]

In [11]:
hasil_xgb = pd.DataFrame(y_proba_xgb)
hasil_xgb

             0
0     0.987140
1     0.984477
2     0.996922
3     0.963503
4     0.984810
...        ...
3730  0.986955
3731  0.917417
3732  0.980240
3733  0.778518
3734  0.900921

[3735 rows x 1 columns]

In [12]:
result1 = pd.concat([inter_df, hasil_xgb], axis=1)
result1

     uniprot_id                                            Senyawa         0
0        P05231                               4-aminobenzoic acid   0.987140
1        P05231                                        Citric acid  0.984477
2        P05231                                   L-phenylalanine   0.996922
3        P05231                         Trans-3-indoleacrylic acid  0.963503
4        P05231                                      DL-tryptophan  0.984810
...         ...                                                ...       ...
3730     P25098                                        Murralongin  0.986955
3731     P25098  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...  0.917417
3732     P25098                                  Limonene, (+/-)-   0.980240
3733     P25098                                     Pheophorbide a  0.778518
3734     P25098                                          SB236057   0.900921

[3735 rows x 3 columns]

In [13]:
df_sorted1 = result1.sort_values(by=0, ascending=False)
# df_sorted1 = df_sorted.head(10)
df_sorted1

     uniprot_id               Senyawa         0
2477     P49768      L-phenylalanine   0.999287
3182     P00338      L-phenylalanine   0.999257
2404     P27338         DL-tryptophan  0.999092
1952     P13569      L-phenylalanine   0.999089
2479     P49768         DL-tryptophan  0.999054
...         ...                   ...       ...
1980     P23443  4-aminobenzoic acid   0.048494
1990     P23443           Murralongin  0.044965
1989     P23443               Murraol  0.032541
1992     P23443     Limonene, (+/-)-   0.030858
1987     P23443       Alpha-lapachone  0.026509

[3735 rows x 3 columns]

In [14]:
filter1_df1 = df_sorted1[df_sorted1[0] > 0.95]
filter1_df1

     uniprot_id                                            Senyawa         0
2477     P49768                                   L-phenylalanine   0.999287
3182     P00338                                   L-phenylalanine   0.999257
2404     P27338                                      DL-tryptophan  0.999092
1952     P13569                                   L-phenylalanine   0.999089
2479     P49768                                      DL-tryptophan  0.999054
...         ...                                                ...       ...
537      P31751                                  Limonene, (+/-)-   0.950134
3171     O60885                                        Murrangatin  0.950119
466      P04626                                        Citric acid  0.950109
811      P05412                                        Citric acid  0.950077
86       P05121  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...  0.950054

[2384 rows x 3 columns]

In [15]:
# Membuat distribusi normal dari kolom
# Kita melakukan standarisasi nilai menjadi distribusi normal dengan mean 0 dan std 1
mean_value_xgb = df_sorted1[0].mean()
std_value_xgb = df_sorted1[0].std()
df_sorted1['Z_Score'] = (df_sorted1[0] - mean_value_xgb) / std_value_xgb

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted1

     uniprot_id               Senyawa         0   Z_Score
2477     P49768      L-phenylalanine   0.999287  0.577825
3182     P00338      L-phenylalanine   0.999257  0.577633
2404     P27338         DL-tryptophan  0.999092  0.576553
1952     P13569      L-phenylalanine   0.999089  0.576536
2479     P49768         DL-tryptophan  0.999054  0.576305
...         ...                   ...       ...       ...
1980     P23443  4-aminobenzoic acid   0.048494 -5.621172
1990     P23443           Murralongin  0.044965 -5.644180
1989     P23443               Murraol  0.032541 -5.725183
1992     P23443     Limonene, (+/-)-   0.030858 -5.736153
1987     P23443       Alpha-lapachone  0.026509 -5.764510

[3735 rows x 4 columns]

In [16]:
df_sorted1.to_csv('./predict_xgb.csv', index=False)

In [17]:
mean_value_xgb

0.91066074

In [18]:
std_value_xgb

0.15337846

### Prediksi menggunakan Model MLP

In [31]:
model_mlp = load('mlp_am.joblib')
print(model_mlp)

MLPClassifier(activation='tanh', alpha=0.001, random_state=42)

In [32]:
print(type(model_mlp))

<class 'sklearn.neural_network._multilayer_perceptron.MLPClassifier'>

In [33]:
hasil_prediksi2 = model_mlp.predict(testing_dff)
hasil_prediksi2

array([1., 1., 1., ..., 1., 1., 1.])

In [34]:
proba2 = model_mlp.predict_proba(testing_dff)
proba2

array([[1.04884717e-02, 9.89511528e-01],
       [1.57492048e-04, 9.99842508e-01],
       [5.00470099e-06, 9.99994995e-01],
       ...,
       [1.27592797e-04, 9.99872407e-01],
       [5.19192990e-03, 9.94808070e-01],
       [3.63427351e-06, 9.99996366e-01]])

In [35]:
# Menggunakan .predict_proba() untuk mendapatkan probabilitas prediksi
y_proba_mlp = model_mlp.predict_proba(testing_dff)[:, 1]  # Probabilitas untuk kelas 1

# Menetapkan threshold 0.9 untuk prediksi kelas 1
threshold = 0.95
y_pred_custom = (y_proba_mlp >= threshold).astype(int)

print("Probabilitas prediksi untuk kelas 1:", y_proba_mlp)
print("Prediksi dengan threshold 0.8:", y_pred_custom)

Probabilitas prediksi untuk kelas 1: [0.98951153 0.99984251 0.999995   ... 0.99987241 0.99480807 0.99999637]
Prediksi dengan threshold 0.8: [1 1 1 ... 1 1 1]

In [36]:
hasil_mlp = pd.DataFrame(y_proba_mlp)
hasil_mlp

             0
0     0.989512
1     0.999843
2     0.999995
3     0.999993
4     0.999993
...        ...
3730  0.999993
3731  0.999897
3732  0.999872
3733  0.994808
3734  0.999996

[3735 rows x 1 columns]

In [37]:
result2 = pd.concat([inter_df, hasil_mlp], axis=1)
result2

     uniprot_id                                            Senyawa         0
0        P05231                               4-aminobenzoic acid   0.989512
1        P05231                                        Citric acid  0.999843
2        P05231                                   L-phenylalanine   0.999995
3        P05231                         Trans-3-indoleacrylic acid  0.999993
4        P05231                                      DL-tryptophan  0.999993
...         ...                                                ...       ...
3730     P25098                                        Murralongin  0.999993
3731     P25098  (1R,9S)-5-[(E)-2-(4-chlorophenyl)ethenyl]-11-(...  0.999897
3732     P25098                                  Limonene, (+/-)-   0.999872
3733     P25098                                     Pheophorbide a  0.994808
3734     P25098                                          SB236057   0.999996

[3735 rows x 3 columns]

In [38]:
df_sorted2 = result2.sort_values(by=0, ascending=False)
# df_sorted2 = df_sorted.head(10)
df_sorted2

     uniprot_id               Senyawa         0
89       P05121             SB236057   1.000000
524      P42345             SB236057   1.000000
82       P05121       Alpha-lapachone  1.000000
77       P05121      L-phenylalanine   1.000000
3098     P78527        Hainanmurpanin  1.000000
...         ...                   ...       ...
2835     Q07820  4-aminobenzoic acid   0.000195
2326     O14965           Citric acid  0.000145
15       P04637  4-aminobenzoic acid   0.000125
2331     O14965           Murrangatin  0.000023
3270     P06730  4-aminobenzoic acid   0.000004

[3735 rows x 3 columns]

In [39]:
filter1_df2 = df_sorted2[df_sorted2[0] > 0.95]
filter1_df2

     uniprot_id                     Senyawa         0
89       P05121                   SB236057   1.000000
524      P42345                   SB236057   1.000000
82       P05121             Alpha-lapachone  1.000000
77       P05121            L-phenylalanine   1.000000
3098     P78527              Hainanmurpanin  1.000000
...         ...                         ...       ...
2420     P09874  4-O-feruloyl-D-quinic acid  0.952967
2776     Q14145                 Citric acid  0.952473
787      O14746             Alpha-lapachone  0.951224
3301     P35372                 Citric acid  0.951087
267      P09038           Limonene, (+/-)-   0.951056

[3182 rows x 3 columns]

In [40]:
# Membuat distribusi normal dari kolom
# Kita melakukan standarisasi nilai menjadi distribusi normal dengan mean 0 dan std 1
mean_value_mlp = df_sorted2[0].mean()
std_value_mlp = df_sorted2[0].std()
df_sorted2['Z_Score'] = (df_sorted2[0] - mean_value_mlp) / std_value_mlp

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted2

     uniprot_id               Senyawa         0   Z_Score
89       P05121             SB236057   1.000000  0.336073
524      P42345             SB236057   1.000000  0.336073
82       P05121       Alpha-lapachone  1.000000  0.336073
77       P05121      L-phenylalanine   1.000000  0.336073
3098     P78527        Hainanmurpanin  1.000000  0.336073
...         ...                   ...       ...       ...
2835     Q07820  4-aminobenzoic acid   0.000195 -4.282993
2326     O14965           Citric acid  0.000145 -4.283222
15       P04637  4-aminobenzoic acid   0.000125 -4.283314
2331     O14965           Murrangatin  0.000023 -4.283786
3270     P06730  4-aminobenzoic acid   0.000004 -4.283873

[3735 rows x 4 columns]

In [41]:
df_sorted2.to_csv('./predict_mlp.csv', index=False)

In [42]:
from scipy.stats import norm
# p-value untuk one-tailed (right)
df_sorted2['p_value'] = 1 - norm.cdf(df_sorted2['Z_Score'])

# # Alternatif lain menggunakan scipy.stats.zscore
# df['Z_Score_Alt'] = zscore(df['Values'])

# Output hasil
df_sorted2

     uniprot_id               Senyawa         0   Z_Score   p_value
89       P05121             SB236057   1.000000  0.336073  0.368408
524      P42345             SB236057   1.000000  0.336073  0.368408
82       P05121       Alpha-lapachone  1.000000  0.336073  0.368408
77       P05121      L-phenylalanine   1.000000  0.336073  0.368408
3098     P78527        Hainanmurpanin  1.000000  0.336073  0.368408
...         ...                   ...       ...       ...       ...
2835     Q07820  4-aminobenzoic acid   0.000195 -4.282993  0.999991
2326     O14965           Citric acid  0.000145 -4.283222  0.999991
15       P04637  4-aminobenzoic acid   0.000125 -4.283314  0.999991
2331     O14965           Murrangatin  0.000023 -4.283786  0.999991
3270     P06730  4-aminobenzoic acid   0.000004 -4.283873  0.999991

[3735 rows x 5 columns]

In [33]:
mean_value_mlp

0.9272562875121345

In [34]:
std_value_mlp

0.2164517962224721

### Nama Protein

In [43]:
fasta_df = pd.read_csv('../../../data/fasta/fasta_df_a.csv')
fasta_df

,uniprot_id,protein_name,fasta_seq
0,P05231,IL6_HUMAN,MNSFSTSAFGPVAFSLGLLLVLPAAFPAPVPPGEDSKDVAAPHRQP...
1,P04637,P53_HUMAN,MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLS...
2,Q05469,LIPS_HUMAN,MEPGSKSVSRSDWQPEPHQRPITPLEPGPEKTPIAQPESKTLQGSN...
3,P46531,NOTC1_HUMAN,MPPLLAPLLCLALLPALAARGPRCSQPGETCLNGGKCEAANGTEAC...
4,P00750,TPA_HUMAN,MDAMKRGLCCVLLLCGAVFVSPSQEIHARFRRGARSYQVICRDEKT...
...,...,...,...
1168,Q6PHR2,ULK3_HUMAN,MAGPGWGPPRLDGFILTERLGSGTYATVYKAYAKKDTREVVAIKCV...
1169,Q8NE63,HIPK4_HUMAN,MSTIQSETDCYDIIEVLGKGTFGEVAKGWRRSTGEMVAIKILKNDA...
1170,O94768,ST17B_HUMAN,MSRRRFDCRSISGLLTTTPQIPIKMENFNNFYILTSKELGRGKFAV...
1171,Q9GZN0,GPR88_HUMAN,MTNSSSTSTSSTTGGSLLLLCEEEESWAGRRIPVSLLYSGLAIGGT...
1172,P49354,FNTA_HUMAN,MAATEGVGEAAQGGEPGQPAQPPPQPHPPPPQQQHKEEMAAEAGEA...

In [45]:
rf_pvalue = pd.read_csv('predict_rf_pvalue.csv')
rf_pvalue

   uniprot_id                     Senyawa         0   Z_Score   p_value
0      P28223                 Citric acid  0.987333  1.820573  0.034336
1      P49768                 Citric acid  0.985417  1.806587  0.035413
2      P49768  4-O-feruloyl-D-quinic acid  0.982069  1.782162  0.037361
3      P05106                 Citric acid  0.981821  1.780352  0.037509
4      P14416                 Citric acid  0.980429  1.770189  0.038348
5      Q8NER1  4-O-feruloyl-D-quinic acid  0.980083  1.767669  0.038558
6      P24941              Hainanmurpanin  0.975123  1.731474  0.041684
7      P05106        4-aminobenzoic acid   0.974833  1.729360  0.041872
8      P27338  4-O-feruloyl-D-quinic acid  0.972917  1.715374  0.043138
9      Q92769  Trans-3-indoleacrylic acid  0.972875  1.715070  0.043166
10     P04798              Hainanmurpanin  0.972083  1.709293  0.043698
11     P14416  Trans-3-indoleacrylic acid  0.971125  1.702300  0.044350
12     Q16539                 Citric acid  0.970292  1.696220  0.044922
13     P24941  4-O-feruloyl-D-quinic acid  0.970250  1.695916  0.044951
14     Q92769  4-O-feruloyl-D-quinic acid  0.970042  1.694395  0.045095
15     P04798                 Murralongin  0.969750  1.692267  0.045298
16     P24941                 Murralongin  0.968893  1.686012  0.045897
17     P49768              Hainanmurpanin  0.968528  1.683348  0.046154
18     P27338                 Murralongin  0.967476  1.675675  0.046901
19     Q07869                 Citric acid  0.966740  1.670306  0.047429
20     P49768                 Murralongin  0.966421  1.667973  0.047661
21     P28223            L-phenylalanine   0.964738  1.655695  0.048892
22     P14416  4-O-feruloyl-D-quinic acid  0.964560  1.654392  0.049024
23     Q92769                 Citric acid  0.964313  1.652590  0.049207
24     P27338  Trans-3-indoleacrylic acid  0.964000  1.650309  0.049440
25     Q8NER1                 Murralongin  0.963369  1.645705  0.049912
26     P08253                 Citric acid  0.963333  1.645445  0.049939

In [46]:
rf_pvalue = rf_pvalue.merge(fasta_df[['uniprot_id', 'protein_name']], on='uniprot_id', how='left')
rf_pvalue

,uniprot_id,Senyawa,0,Z_Score,p_value,protein_name
0,P28223,Citric acid,0.987333,1.820573,0.034336,5HT2A_HUMAN
1,P49768,Citric acid,0.985417,1.806587,0.035413,PSN1_HUMAN
2,P49768,4-O-feruloyl-D-quinic acid,0.982069,1.782162,0.037361,PSN1_HUMAN
3,P05106,Citric acid,0.981821,1.780352,0.037509,ITB3_HUMAN
4,P14416,Citric acid,0.980429,1.770189,0.038348,DRD2_HUMAN
5,Q8NER1,4-O-feruloyl-D-quinic acid,0.980083,1.767669,0.038558,TRPV1_HUMAN
6,P24941,Hainanmurpanin,0.975123,1.731474,0.041684,CDK2_HUMAN
7,P05106,4-aminobenzoic acid,0.974833,1.729360,0.041872,ITB3_HUMAN
8,P27338,4-O-feruloyl-D-quinic acid,0.972917,1.715374,0.043138,AOFB_HUMAN
9,Q92769,Trans-3-indoleacrylic acid,0.972875,1.715070,0.043166,HDAC2_HUMAN
10,P04798,Hainanmurpanin,0.972083,1.709293,0.043698,CP1A1_HUMAN
11,P14416,Trans-3-indoleacrylic acid,0.971125,1.702300,0.044350,DRD2_HUMAN
12,Q16539,Citric acid,0.970292,1.696220,0.044922,MK14_HUMAN
13,P24941,4-O-feruloyl-D-quinic acid,0.970250,1.695916,0.044951,CDK2_HUMAN
14,Q92769,4-O-feruloyl-D-quinic acid,0.970042,1.694395,0.045095,HDAC2_HUMAN
15,P04798,Murralongin,0.969750,1.692267,0.045298,CP1A1_HUMAN
16,P24941,Murralongin,0.968893,1.686012,0.045897,CDK2_HUMAN
17,P49768,Hainanmurpanin,0.968528,1.683348,0.046154,PSN1_HUMAN
18,P27338,Murralongin,0.967476,1.675675,0.046901,AOFB_HUMAN
19,Q07869,Citric acid,0.966740,1.670306,0.047429,PPARA_HUMAN
20,P49768,Murralongin,0.966421,1.667973,0.047661,PSN1_HUMAN
21,P28223,L-phenylalanine,0.964738,1.655695,0.048892,5HT2A_HUMAN
22,P14416,4-O-feruloyl-D-quinic acid,0.964560,1.654392,0.049024,DRD2_HUMAN
23,Q92769,Citric acid,0.964313,1.652590,0.049207,HDAC2_HUMAN
24,P27338,Trans-3-indoleacrylic acid,0.964000,1.650309,0.049440,AOFB_HUMAN
25,Q8NER1,Murralongin,0.963369,1.645705,0.049912,TRPV1_HUMAN
26,P08253,Citric acid,0.963333,1.645445,0.049939,MMP2_HUMAN

In [47]:
rf_pvalue.to_csv('./predict_rf_senyawaname.csv', index=False)

### Hasil Prediksi 3 Model

In [37]:
result_rf = pd.read_csv('./predict_rf.csv') 
result_rf

     uniprot_id                     Senyawa         0   Z_Score
0        P28223                 Citric acid  0.987333  1.820573
1        P49768                 Citric acid  0.985417  1.806587
2        P49768  4-O-feruloyl-D-quinic acid  0.982069  1.782162
3        P05106                 Citric acid  0.981821  1.780352
4        P14416                 Citric acid  0.980429  1.770189
...         ...                         ...       ...       ...
3730     O43521                 Murralongin  0.194894 -3.961865
3731     O43521  Trans-3-indoleacrylic acid  0.181222 -4.061630
3732     O43521            L-phenylalanine   0.171693 -4.131165
3733     O43521                 Citric acid  0.157949 -4.231457
3734     O43521        4-aminobenzoic acid   0.110333 -4.578907

[3735 rows x 4 columns]

In [35]:
df_sorted1 #XGBoost

     uniprot_id               Senyawa         0   Z_Score
2477     P49768      L-phenylalanine   0.999287  0.577825
3182     P00338      L-phenylalanine   0.999257  0.577633
2404     P27338         DL-tryptophan  0.999092  0.576553
1952     P13569      L-phenylalanine   0.999089  0.576536
2479     P49768         DL-tryptophan  0.999054  0.576305
...         ...                   ...       ...       ...
1980     P23443  4-aminobenzoic acid   0.048494 -5.621172
1990     P23443           Murralongin  0.044965 -5.644180
1989     P23443               Murraol  0.032541 -5.725183
1992     P23443     Limonene, (+/-)-   0.030858 -5.736153
1987     P23443       Alpha-lapachone  0.026509 -5.764510

[3735 rows x 4 columns]

In [36]:
df_sorted2 #MLP

     uniprot_id               Senyawa         0   Z_Score
89       P05121             SB236057   1.000000  0.336073
524      P42345             SB236057   1.000000  0.336073
82       P05121       Alpha-lapachone  1.000000  0.336073
77       P05121      L-phenylalanine   1.000000  0.336073
3098     P78527        Hainanmurpanin  1.000000  0.336073
...         ...                   ...       ...       ...
2835     Q07820  4-aminobenzoic acid   0.000195 -4.282993
2326     O14965           Citric acid  0.000145 -4.283222
15       P04637  4-aminobenzoic acid   0.000125 -4.283314
2331     O14965           Murrangatin  0.000023 -4.283786
3270     P06730  4-aminobenzoic acid   0.000004 -4.283873

[3735 rows x 4 columns]